drop table Progresses
drop table Enrollments
drop table LearningObjects
drop table Courses
drop table ClientProfiles
drop table CourseCategories
drop table JobPositions
drop table Filials
drop table SaleGroups
drop table AssessmentQuestions
drop table Assessments
drop table Answers
drop table Questions
drop table ProgressStates
drop table AspNetUserRoles
drop table AspNetUserLogins
drop table AspNetUserClaims
drop table AspNetUsers
drop table AspNetRoles
drop table __MigrationHistory